### ISSUE TITLE
Not all emoji work

### ISSUE THREAD

**Issue by DaVince** [Spuds/ElkArte-Emoji#2]
For some reason, only some emoji work while others won't. It's not clear to me why, as the emoji *do* appear when editing a post.

See http://www.spheredev.org/ElkArte/index.php/topic,1459.msg9104.html#msg9104 for an example.

**Comment by Spuds** [comment]
Looks like its not picking them up when there is no leading space ... I can upload a new file for you to test or you can edit the ```Emoji.class.php``` file that is located in sources/subs

find ```				$parts[$i] = preg_replace_callback('~(\s|^|\])(:([-+\w]+):\s?)~si', 'Emoji::_emojiToImage_Callback', $parts[$i]);```

replace that with  ```				$parts[$i] = preg_replace_callback('~(\s?|^|\]|<br \/>)(:([-+\w]+):\s?)~si', 'Emoji::_emojiToImage_Callback', $parts[$i]);```

That will loosen the "rules" a bit and should render the ones you showed in that post.

Also the 777 thing is most likely a mismatch in the user / group name that your web server is running under (Apache / nginx), typically something like www-user:www-data and the ftp/user id that you uploaded your files, its not something the forum software does,

**Comment by DaVince** [comment]
this fixed emoji entirely. Thanks for the quick follow-up! :smile:
