### ISSUE TITLE
Error strtr() expects at most 3 parameters, 4 given

### ISSUE THREAD

**Issue by emanuele45** [Spuds/ElkArte-Emoji#4]
Little typo with strtr at https://github.com/Spuds/ElkArte-Emoji/blob/master/Emoji.integration.php#L70

reported by @AlexL777 at https://github.com/elkarte/Elkarte/issues/3033

**Comment by Spuds** [comment]
Grrrr .. fixed in https://github.com/Spuds/ElkArte-Emoji/commit/c2e4af90441fae2274b15c4621fe55438841f88a
